- hosts: all
  become: yes
  gather_facts: yes

  vars:  
    hostname: eth-node
    eth_private_ip: 192.168.1.2/24
    private_ip_config: /etc/netplan/private.yml

    device: /dev/vdb
    mount_path: /ethdata

    nomad_ver: https://releases.hashicorp.com/nomad/1.1.2/nomad_1.1.2_linux_amd64.zip
    bin_path: /usr/local/bin
    
    cni_plugin: https://github.com/containernetworking/plugins/releases/download/v0.9.1/cni-plugins-linux-amd64-v0.9.1.tgz
    cni_folder: /opt/cni/bin
    

  roles:
    - system
    - nomad
    - deploy-eth

