---
# tasks file for system

# Hostname for target machine
- name: Set hostname
  hostname:
    name: "{{ hostname }}"

# Network configuration
- name: set private interface configuration
  template:
    src: private.yml.j2
    dest: "{{ private_ip_config }}"
    owner: root
    group: root
    mode: 0644

- name: netplan config apply
  command: netplan apply
  async: 100
  poll: 0

# Disk configuration for ETH data
- name: Check if already done
  stat:
    path: "{{ mount_path }}"
  register: ethdata

- parted:
    device: "{{ device }}"
    number: 1
    state: present
  when: ethdata.stat.exists == false

- filesystem:
    fstype: ext4
    dev: "{{ device }}"
  when: ethdata.stat.exists == false

- mount:
    path: "{{ mount_path }}"
    src: "{{ device }}"
    fstype: ext4
    boot: yes
    opts: noatime,nofail
    state: mounted
  when: ethdata.stat.exists == false