---
# tasks file for system

# Hostname for target machine
- name: Set hostname
  hostname:
    name: "{{ hostname }}"

# Network configuration
- name: check network
  shell: |
    ip link show ens4
  register: net_status
  ignore_errors: true

- name: provide IP if not yet
  shell: |
    ip a add 192.168.1.2/24 dev ens4
  become: yes
  when: "'192.168.1.2' not in net_status.stdout"

- name: enable ens4 if not yet
  shell: |
    ip link set ens4 up
  become: yes
  when: "'UP' not in net_status.stdout"
 
# Disk configuration for ETH data
- name: Check if already done
  stat:
    path: "{{ mount_path }}"
  register: ethdata

- parted:
    device: "{{ device }}"
    number: 1
    state: present
  when: ethdata.stat.exists == false

- filesystem:
    fstype: ext4
    dev: "{{ device }}"
  when: ethdata.stat.exists == false

- mount:
    path: "{{ mount_path }}"
    src: "{{ device }}"
    fstype: ext4
    boot: yes
    opts: noatime,nofail
    state: mounted
  when: ethdata.stat.exists == false
