---
# tasks file for system

# Hostname for target machine
- name: Set hostname
  hostname:
    name: "{{ hostname }}"

# Network configuration
- name: enable network interface and set ip
  shell: |
    ip a add 192.168.1.2/24 dev ens4 && ip link set ens4 up
  become: yes

# Disk configuration for ETH data
- name: Check if already done
  stat:
    path: "{{ mount_path }}"
  register: ethdata

- parted:
    device: "{{ device }}"
    number: 1
    state: present
  when: ethdata.stat.exists == false

- filesystem:
    fstype: ext4
    dev: "{{ device }}"
  when: ethdata.stat.exists == false

- mount:
    path: "{{ mount_path }}"
    src: "{{ device }}"
    fstype: ext4
    boot: yes
    opts: noatime,nofail
    state: mounted
  when: ethdata.stat.exists == false