---
# tasks file for system

- name: install dependencies
  package:
    state: present
    name:
      - unzip

- name: extract and install nomad
  unarchive:
    src: "{{ nomad_ver }}"
    dest: "/tmp/"
    remote_src: true

- name: copy nomad to bin path
  copy:
    remote_src: true
    src: "/tmp/nomad"
    dest: "{{ bin_path }}/nomad"
    mode: 0755

- name: Copy config file
  template:
    src: "nomad.hcl.j2"
    dest: "{{ bin_path }}/nomad.hcl"
    owner: root
    group: root
    force: yes

- name: Copy systemd nomad template
  template:
    src: nomad.service.j2
    dest: "/etc/systemd/system/nomad.service"

- name: Create dir for CNI
  file:
    path: "{{ cni_folder }}"
    state: directory

- name: install CNI plugins for nomad # for bridge mode in nomad network
  unarchive:
    src: "{{ cni_plugin }}"
    dest: "{{ cni_folder }}"
    remote_src: true

- name: Start nomad service
  systemd:
    daemon_reload: yes
    state: restarted
    enabled: yes
    name: nomad.service

